/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface OtherComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLOtherComponentElement extends Components.OtherComponent, HTMLStencilElement {}
  var HTMLOtherComponentElement: {
    prototype: HTMLOtherComponentElement;
    new (): HTMLOtherComponentElement;
  };
  interface HTMLElementTagNameMap {
    'other-component': HTMLOtherComponentElement;
  }
}

declare namespace LocalJSX {
  interface OtherComponent extends JSXBase.HTMLAttributes<HTMLOtherComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'other-component': OtherComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


